"""create_users_cases_transcriptions_tables

Revision ID: fe8d33c28e88
Revises: d04bb612eec6
Create Date: 2026-04-23 16:17:06.371348+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fe8d33c28e88'
down_revision: Union[str, None] = 'd04bb612eec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('email_hash', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('owner', 'admin', 'member')", name='users_role_check'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email_hash')
    )
    op.create_index('ix_users_organization_id', 'users', ['organization_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cases_organization_id_created_at', 'cases', ['organization_id', 'created_at'], unique=False)
    op.create_table('transcriptions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('audio_s3_key', sa.Text(), nullable=True),
    sa.Column('audio_duration_s', sa.Integer(), nullable=True),
    sa.Column('audio_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('audio_format', sa.Text(), nullable=True),
    sa.Column('audio_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('progress_pct', sa.SmallInteger(), nullable=True),
    sa.Column('language', sa.Text(), server_default='fr', nullable=False),
    sa.Column('speaker_count', sa.SmallInteger(), nullable=True),
    sa.Column('transcript_s3_key', sa.Text(), nullable=True),
    sa.Column('transcript_preview', sa.Text(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_minutes_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transcriptions_org_created_at', 'transcriptions', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_transcriptions_org_status', 'transcriptions', ['organization_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transcriptions_org_status', table_name='transcriptions')
    op.drop_index('ix_transcriptions_org_created_at', table_name='transcriptions')
    op.drop_table('transcriptions')
    op.drop_index('ix_cases_organization_id_created_at', table_name='cases')
    op.drop_table('cases')
    op.drop_index('ix_users_organization_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
