"""add_transcription_segments_table

Revision ID: 752a4e2476c1
Revises: 4d3561b59475
Create Date: 2026-04-27 12:43:00.622359+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '752a4e2476c1'
down_revision: Union[str, None] = '4d3561b59475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcription_segments',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('transcription_id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Text(), nullable=True),
    sa.Column('start_s', sa.Double(), nullable=False),
    sa.Column('end_s', sa.Double(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_segments_org_id', 'transcription_segments', ['organization_id'], unique=False)
    op.create_index('ix_segments_transcription_id', 'transcription_segments', ['transcription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_segments_transcription_id', table_name='transcription_segments')
    op.drop_index('ix_segments_org_id', table_name='transcription_segments')
    op.drop_table('transcription_segments')
    # ### end Alembic commands ###
